/**
 * TransferZero API
 * Reference documentation for the TransferZero API V1
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PayinMethodDetailsMobile from './PayinMethodDetailsMobile';
import PayinMethodDetailsNGNBank from './PayinMethodDetailsNGNBank';

/**
 * The PayinMethodDetails model module.
 * @module Model/PayinMethodDetails
 * @version 1.0.0
 */
class PayinMethodDetails {
    /**
     * Constructs a new <code>PayinMethodDetails</code>.
     * Fields needed by the payment processor. Depends on the chose payin type.  See the appropriate model details for more info:  - &#x60;NGN::Bank&#x60;: see [&#x60;PayinMethodDetailsNGNBank&#x60;](#model-PayinMethodDetailsNGNBank) - &#x60;GHS::Mobile&#x60;: see [&#x60;PayinMethodDetailsMobile&#x60;](#model-PayinMethodDetailsMobile) - &#x60;UGX::Mobile&#x60;: see [&#x60;PayinMethodDetailsMobile&#x60;](#model-PayinMethodDetailsMobile) - &#x60;TZS::Mobile&#x60;: see [&#x60;PayinMethodDetailsMobile&#x60;](#model-PayinMethodDetailsMobile) 
     * @alias module:Model/PayinMethodDetails
     * @implements module:Model/PayinMethodDetailsNGNBank
     * @implements module:Model/PayinMethodDetailsMobile
     * @param redirectUrl {} This is where the user should be redirected back when the payment has been finished
     * @param phoneNumber {} The phone number where the funds should be collected from
     */
    constructor(redirectUrl, phoneNumber) { 
        PayinMethodDetailsNGNBank.initialize(this, redirectUrl);PayinMethodDetailsMobile.initialize(this, phoneNumber);
        PayinMethodDetails.initialize(this, redirectUrl, phoneNumber);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, redirectUrl, phoneNumber) { 
    }

    /**
     * Constructs a <code>PayinMethodDetails</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Model/PayinMethodDetails} obj Optional instance to populate.
     * @return {module:Model/PayinMethodDetails} The populated <code>PayinMethodDetails</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PayinMethodDetails();
            PayinMethodDetailsNGNBank.constructFromObject(data, obj);
            PayinMethodDetailsMobile.constructFromObject(data, obj);

        }
        return obj;
    }


}


// Implement PayinMethodDetailsNGNBank interface:
/**
 * This is where the user should be redirected back when the payment has been finished
 * @member {String} redirect_url
 */
PayinMethodDetailsNGNBank.prototype['redirect_url'] = undefined;
// Implement PayinMethodDetailsMobile interface:
/**
 * The phone number where the funds should be collected from
 * @member {String} phone_number
 */
PayinMethodDetailsMobile.prototype['phone_number'] = undefined;
/**
 * States whether to send out the instructions to the phone number on how to pay the funds or not. This shuold always be set to true, otherwise the sender might not receive a prompt for payment.
 * @member {Boolean} send_instructions
 */
PayinMethodDetailsMobile.prototype['send_instructions'] = undefined;




export default PayinMethodDetails;

