/**
 * BitPesa API
 * Reference documentation for the BitPesa API V1
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PayoutMethodBankAccountTypeEnum from './PayoutMethodBankAccountTypeEnum';
import PayoutMethodDetailsBalance from './PayoutMethodDetailsBalance';
import PayoutMethodDetailsGHSBank from './PayoutMethodDetailsGHSBank';
import PayoutMethodDetailsIBAN from './PayoutMethodDetailsIBAN';
import PayoutMethodDetailsMADCash from './PayoutMethodDetailsMADCash';
import PayoutMethodDetailsMobile from './PayoutMethodDetailsMobile';
import PayoutMethodDetailsNGNBank from './PayoutMethodDetailsNGNBank';
import PayoutMethodDetailsXOFMobile from './PayoutMethodDetailsXOFMobile';
import PayoutMethodGenderEnum from './PayoutMethodGenderEnum';
import PayoutMethodIdentityCardTypeEnum from './PayoutMethodIdentityCardTypeEnum';
import PayoutMethodMobileProviderEnum from './PayoutMethodMobileProviderEnum';

/**
 * The PayoutMethodDetails model module.
 * @module Model/PayoutMethodDetails
 * @version 0.2.0
 */
class PayoutMethodDetails {
    /**
     * Constructs a new <code>PayoutMethodDetails</code>.
     * @alias module:Model/PayoutMethodDetails
     * @implements module:Model/PayoutMethodDetailsNGNBank
     * @implements module:Model/PayoutMethodDetailsMobile
     * @implements module:Model/PayoutMethodDetailsXOFMobile
     * @implements module:Model/PayoutMethodDetailsGHSBank
     * @implements module:Model/PayoutMethodDetailsIBAN
     * @implements module:Model/PayoutMethodDetailsMADCash
     * @implements module:Model/PayoutMethodDetailsBalance
     */
    constructor() { 
        PayoutMethodDetailsNGNBank.initialize(this, firstName, lastName, bankCode, bankAccount, bankAccountType);PayoutMethodDetailsMobile.initialize(this, firstName, lastName, phoneNumber);PayoutMethodDetailsXOFMobile.initialize(this, firstName, lastName, phoneNumber, mobileProvider);PayoutMethodDetailsGHSBank.initialize(this, firstName, lastName, bankCode, bankAccount);PayoutMethodDetailsIBAN.initialize(this, firstName, lastName, bankName, iban);PayoutMethodDetailsMADCash.initialize(this, firstName, lastName, phoneNumber, senderIdentityCardType, senderIdentityCardId, senderCityOfBirth, senderCountryOfBirth, senderGender);PayoutMethodDetailsBalance.initialize(this);
        PayoutMethodDetails.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
        obj['first_name'] = firstName;
        obj['last_name'] = lastName;
        obj['bank_code'] = bankCode;
        obj['bank_account'] = bankAccount;
        obj['bank_account_type'] = bankAccountType;
        obj['phone_number'] = phoneNumber;
        obj['mobile_provider'] = mobileProvider;
        obj['bank_name'] = bankName;
        obj['iban'] = iban;
        obj['sender_identity_card_type'] = senderIdentityCardType;
        obj['sender_identity_card_id'] = senderIdentityCardId;
        obj['sender_city_of_birth'] = senderCityOfBirth;
        obj['sender_country_of_birth'] = senderCountryOfBirth;
        obj['sender_gender'] = senderGender;
    }

    /**
     * Constructs a <code>PayoutMethodDetails</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Model/PayoutMethodDetails} obj Optional instance to populate.
     * @return {module:Model/PayoutMethodDetails} The populated <code>PayoutMethodDetails</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PayoutMethodDetails();
            PayoutMethodDetailsNGNBank.constructFromObject(data, obj);
            PayoutMethodDetailsMobile.constructFromObject(data, obj);
            PayoutMethodDetailsXOFMobile.constructFromObject(data, obj);
            PayoutMethodDetailsGHSBank.constructFromObject(data, obj);
            PayoutMethodDetailsIBAN.constructFromObject(data, obj);
            PayoutMethodDetailsMADCash.constructFromObject(data, obj);
            PayoutMethodDetailsBalance.constructFromObject(data, obj);

            if (data.hasOwnProperty('first_name')) {
                obj['first_name'] = ApiClient.convertToType(data['first_name'], 'String');
            }
            if (data.hasOwnProperty('last_name')) {
                obj['last_name'] = ApiClient.convertToType(data['last_name'], 'String');
            }
            if (data.hasOwnProperty('bank_code')) {
                obj['bank_code'] = ApiClient.convertToType(data['bank_code'], 'String');
            }
            if (data.hasOwnProperty('bank_account')) {
                obj['bank_account'] = ApiClient.convertToType(data['bank_account'], 'String');
            }
            if (data.hasOwnProperty('bank_account_type')) {
                obj['bank_account_type'] = PayoutMethodBankAccountTypeEnum.constructFromObject(data['bank_account_type']);
            }
            if (data.hasOwnProperty('phone_number')) {
                obj['phone_number'] = ApiClient.convertToType(data['phone_number'], 'String');
            }
            if (data.hasOwnProperty('mobile_provider')) {
                obj['mobile_provider'] = PayoutMethodMobileProviderEnum.constructFromObject(data['mobile_provider']);
            }
            if (data.hasOwnProperty('bank_name')) {
                obj['bank_name'] = ApiClient.convertToType(data['bank_name'], 'String');
            }
            if (data.hasOwnProperty('iban')) {
                obj['iban'] = ApiClient.convertToType(data['iban'], 'String');
            }
            if (data.hasOwnProperty('bic')) {
                obj['bic'] = ApiClient.convertToType(data['bic'], 'String');
            }
            if (data.hasOwnProperty('sender_identity_card_type')) {
                obj['sender_identity_card_type'] = PayoutMethodIdentityCardTypeEnum.constructFromObject(data['sender_identity_card_type']);
            }
            if (data.hasOwnProperty('sender_identity_card_id')) {
                obj['sender_identity_card_id'] = ApiClient.convertToType(data['sender_identity_card_id'], 'String');
            }
            if (data.hasOwnProperty('sender_city_of_birth')) {
                obj['sender_city_of_birth'] = ApiClient.convertToType(data['sender_city_of_birth'], 'String');
            }
            if (data.hasOwnProperty('sender_country_of_birth')) {
                obj['sender_country_of_birth'] = ApiClient.convertToType(data['sender_country_of_birth'], 'String');
            }
            if (data.hasOwnProperty('sender_gender')) {
                obj['sender_gender'] = PayoutMethodGenderEnum.constructFromObject(data['sender_gender']);
            }
            if (data.hasOwnProperty('reason')) {
                obj['reason'] = ApiClient.convertToType(data['reason'], 'String');
            }
            if (data.hasOwnProperty('identity_card_type')) {
                obj['identity_card_type'] = PayoutMethodIdentityCardTypeEnum.constructFromObject(data['identity_card_type']);
            }
            if (data.hasOwnProperty('identity_card_id')) {
                obj['identity_card_id'] = ApiClient.convertToType(data['identity_card_id'], 'String');
            }
            if (data.hasOwnProperty('reference')) {
                obj['reference'] = ApiClient.convertToType(data['reference'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} first_name
 */
PayoutMethodDetails.prototype['first_name'] = undefined;

/**
 * @member {String} last_name
 */
PayoutMethodDetails.prototype['last_name'] = undefined;

/**
 * @member {String} bank_code
 */
PayoutMethodDetails.prototype['bank_code'] = undefined;

/**
 * @member {String} bank_account
 */
PayoutMethodDetails.prototype['bank_account'] = undefined;

/**
 * @member {module:Model/PayoutMethodBankAccountTypeEnum} bank_account_type
 */
PayoutMethodDetails.prototype['bank_account_type'] = undefined;

/**
 * @member {String} phone_number
 */
PayoutMethodDetails.prototype['phone_number'] = undefined;

/**
 * @member {module:Model/PayoutMethodMobileProviderEnum} mobile_provider
 */
PayoutMethodDetails.prototype['mobile_provider'] = undefined;

/**
 * @member {String} bank_name
 */
PayoutMethodDetails.prototype['bank_name'] = undefined;

/**
 * @member {String} iban
 */
PayoutMethodDetails.prototype['iban'] = undefined;

/**
 * @member {String} bic
 */
PayoutMethodDetails.prototype['bic'] = undefined;

/**
 * @member {module:Model/PayoutMethodIdentityCardTypeEnum} sender_identity_card_type
 */
PayoutMethodDetails.prototype['sender_identity_card_type'] = undefined;

/**
 * @member {String} sender_identity_card_id
 */
PayoutMethodDetails.prototype['sender_identity_card_id'] = undefined;

/**
 * @member {String} sender_city_of_birth
 */
PayoutMethodDetails.prototype['sender_city_of_birth'] = undefined;

/**
 * @member {String} sender_country_of_birth
 */
PayoutMethodDetails.prototype['sender_country_of_birth'] = undefined;

/**
 * @member {module:Model/PayoutMethodGenderEnum} sender_gender
 */
PayoutMethodDetails.prototype['sender_gender'] = undefined;

/**
 * @member {String} reason
 */
PayoutMethodDetails.prototype['reason'] = undefined;

/**
 * @member {module:Model/PayoutMethodIdentityCardTypeEnum} identity_card_type
 */
PayoutMethodDetails.prototype['identity_card_type'] = undefined;

/**
 * @member {String} identity_card_id
 */
PayoutMethodDetails.prototype['identity_card_id'] = undefined;

/**
 * @member {String} reference
 */
PayoutMethodDetails.prototype['reference'] = undefined;


// Implement PayoutMethodDetailsNGNBank interface:
/**
 * @member {String} first_name
 */
PayoutMethodDetailsNGNBank.prototype['first_name'] = undefined;
/**
 * @member {String} last_name
 */
PayoutMethodDetailsNGNBank.prototype['last_name'] = undefined;
/**
 * @member {String} bank_code
 */
PayoutMethodDetailsNGNBank.prototype['bank_code'] = undefined;
/**
 * @member {String} bank_account
 */
PayoutMethodDetailsNGNBank.prototype['bank_account'] = undefined;
/**
 * @member {module:Model/PayoutMethodBankAccountTypeEnum} bank_account_type
 */
PayoutMethodDetailsNGNBank.prototype['bank_account_type'] = undefined;
// Implement PayoutMethodDetailsMobile interface:
/**
 * @member {String} first_name
 */
PayoutMethodDetailsMobile.prototype['first_name'] = undefined;
/**
 * @member {String} last_name
 */
PayoutMethodDetailsMobile.prototype['last_name'] = undefined;
/**
 * @member {String} phone_number
 */
PayoutMethodDetailsMobile.prototype['phone_number'] = undefined;
// Implement PayoutMethodDetailsXOFMobile interface:
/**
 * @member {String} first_name
 */
PayoutMethodDetailsXOFMobile.prototype['first_name'] = undefined;
/**
 * @member {String} last_name
 */
PayoutMethodDetailsXOFMobile.prototype['last_name'] = undefined;
/**
 * @member {String} phone_number
 */
PayoutMethodDetailsXOFMobile.prototype['phone_number'] = undefined;
/**
 * @member {module:Model/PayoutMethodMobileProviderEnum} mobile_provider
 */
PayoutMethodDetailsXOFMobile.prototype['mobile_provider'] = undefined;
// Implement PayoutMethodDetailsGHSBank interface:
/**
 * @member {String} first_name
 */
PayoutMethodDetailsGHSBank.prototype['first_name'] = undefined;
/**
 * @member {String} last_name
 */
PayoutMethodDetailsGHSBank.prototype['last_name'] = undefined;
/**
 * @member {String} bank_code
 */
PayoutMethodDetailsGHSBank.prototype['bank_code'] = undefined;
/**
 * @member {String} bank_account
 */
PayoutMethodDetailsGHSBank.prototype['bank_account'] = undefined;
// Implement PayoutMethodDetailsIBAN interface:
/**
 * @member {String} first_name
 */
PayoutMethodDetailsIBAN.prototype['first_name'] = undefined;
/**
 * @member {String} last_name
 */
PayoutMethodDetailsIBAN.prototype['last_name'] = undefined;
/**
 * @member {String} bank_name
 */
PayoutMethodDetailsIBAN.prototype['bank_name'] = undefined;
/**
 * @member {String} iban
 */
PayoutMethodDetailsIBAN.prototype['iban'] = undefined;
/**
 * @member {String} bic
 */
PayoutMethodDetailsIBAN.prototype['bic'] = undefined;
// Implement PayoutMethodDetailsMADCash interface:
/**
 * @member {String} first_name
 */
PayoutMethodDetailsMADCash.prototype['first_name'] = undefined;
/**
 * @member {String} last_name
 */
PayoutMethodDetailsMADCash.prototype['last_name'] = undefined;
/**
 * @member {String} phone_number
 */
PayoutMethodDetailsMADCash.prototype['phone_number'] = undefined;
/**
 * @member {module:Model/PayoutMethodIdentityCardTypeEnum} sender_identity_card_type
 */
PayoutMethodDetailsMADCash.prototype['sender_identity_card_type'] = undefined;
/**
 * @member {String} sender_identity_card_id
 */
PayoutMethodDetailsMADCash.prototype['sender_identity_card_id'] = undefined;
/**
 * @member {String} sender_city_of_birth
 */
PayoutMethodDetailsMADCash.prototype['sender_city_of_birth'] = undefined;
/**
 * @member {String} sender_country_of_birth
 */
PayoutMethodDetailsMADCash.prototype['sender_country_of_birth'] = undefined;
/**
 * @member {module:Model/PayoutMethodGenderEnum} sender_gender
 */
PayoutMethodDetailsMADCash.prototype['sender_gender'] = undefined;
/**
 * @member {String} reason
 */
PayoutMethodDetailsMADCash.prototype['reason'] = undefined;
/**
 * @member {module:Model/PayoutMethodIdentityCardTypeEnum} identity_card_type
 */
PayoutMethodDetailsMADCash.prototype['identity_card_type'] = undefined;
/**
 * @member {String} identity_card_id
 */
PayoutMethodDetailsMADCash.prototype['identity_card_id'] = undefined;
// Implement PayoutMethodDetailsBalance interface:
/**
 * @member {String} reference
 */
PayoutMethodDetailsBalance.prototype['reference'] = undefined;




export default PayoutMethodDetails;

