/**
 * TransferZero API
 * Reference documentation for the TransferZero API V1
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class PayoutMethodMobileProviderEnum.
* @enum {}
* @readonly
*/
export default class PayoutMethodMobileProviderEnum {
    
        /**
         * value: "orange"
         * @const
         */
        "orange" = "orange";

    
        /**
         * value: "tigo"
         * @const
         */
        "tigo" = "tigo";

    

    /**
    * Returns a <code>PayoutMethodMobileProviderEnum</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:Model/PayoutMethodMobileProviderEnum} The enum <code>PayoutMethodMobileProviderEnum</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

