/**
 * BitPesa API
 * Reference documentation for the BitPesa API V1
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Sender from './Sender';
import Webhook from './Webhook';

/**
 * The SenderWebhook model module.
 * @module Model/SenderWebhook
 * @version 0.2.0
 */
class SenderWebhook {
    /**
     * Constructs a new <code>SenderWebhook</code>.
     * @alias module:Model/SenderWebhook
     * @implements module:Model/Webhook
     */
    constructor() { 
        Webhook.initialize(this, webhook, event, _object);
        SenderWebhook.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
        obj['webhook'] = webhook;
        obj['event'] = event;
        obj['object'] = _object;
    }

    /**
     * Constructs a <code>SenderWebhook</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Model/SenderWebhook} obj Optional instance to populate.
     * @return {module:Model/SenderWebhook} The populated <code>SenderWebhook</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SenderWebhook();
            Webhook.constructFromObject(data, obj);

            if (data.hasOwnProperty('webhook')) {
                obj['webhook'] = ApiClient.convertToType(data['webhook'], 'String');
            }
            if (data.hasOwnProperty('event')) {
                obj['event'] = ApiClient.convertToType(data['event'], 'String');
            }
            if (data.hasOwnProperty('object')) {
                obj['object'] = Sender.constructFromObject(data['object']);
            }
        }
        return obj;
    }


}

/**
 * The ID of the webhook that was used to send out this callback
 * @member {String} webhook
 */
SenderWebhook.prototype['webhook'] = undefined;

/**
 * The event that triggered this webhook
 * @member {String} event
 */
SenderWebhook.prototype['event'] = undefined;

/**
 * @member {module:Model/Sender} object
 */
SenderWebhook.prototype['object'] = undefined;


// Implement Webhook interface:
/**
 * The ID of the webhook that was used to send out this callback
 * @member {String} webhook
 */
Webhook.prototype['webhook'] = undefined;
/**
 * The event that triggered this webhook
 * @member {String} event
 */
Webhook.prototype['event'] = undefined;
/**
 * The returned object
 * @member {Object} object
 */
Webhook.prototype['object'] = undefined;




export default SenderWebhook;

