/**
 * TransferZero API
 * Reference documentation for the TransferZero API V1
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class SenderState.
* @enum {}
* @readonly
*/
export default class SenderState {
    
        /**
         * value: "initial"
         * @const
         */
        "initial" = "initial";

    
        /**
         * value: "verified"
         * @const
         */
        "verified" = "verified";

    
        /**
         * value: "approved"
         * @const
         */
        "approved" = "approved";

    
        /**
         * value: "banned"
         * @const
         */
        "banned" = "banned";

    
        /**
         * value: "rejected"
         * @const
         */
        "rejected" = "rejected";

    
        /**
         * value: "disabled"
         * @const
         */
        "disabled" = "disabled";

    

    /**
    * Returns a <code>SenderState</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:Model/SenderState} The enum <code>SenderState</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

