/**
 * TransferZero API
 * Reference documentation for the TransferZero API V1
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class TransactionState.
* @enum {}
* @readonly
*/
export default class TransactionState {
    
        /**
         * value: "initial"
         * @const
         */
        "initial" = "initial";

    
        /**
         * value: "approved"
         * @const
         */
        "approved" = "approved";

    
        /**
         * value: "pending"
         * @const
         */
        "pending" = "pending";

    
        /**
         * value: "received"
         * @const
         */
        "received" = "received";

    
        /**
         * value: "mispaid"
         * @const
         */
        "mispaid" = "mispaid";

    
        /**
         * value: "manual"
         * @const
         */
        "manual" = "manual";

    
        /**
         * value: "paid"
         * @const
         */
        "paid" = "paid";

    
        /**
         * value: "canceled"
         * @const
         */
        "canceled" = "canceled";

    
        /**
         * value: "refunded"
         * @const
         */
        "refunded" = "refunded";

    
        /**
         * value: "exception"
         * @const
         */
        "exception" = "exception";

    

    /**
    * Returns a <code>TransactionState</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:Model/TransactionState} The enum <code>TransactionState</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

