/**
 * TransferZero API
 * Reference documentation for the TransferZero API V1
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ValidationErrorDescription model module.
 * @module Model/ValidationErrorDescription
 * @version 1.0.0
 */
class ValidationErrorDescription {
    /**
     * Constructs a new <code>ValidationErrorDescription</code>.
     * The description of the error
     * @alias module:Model/ValidationErrorDescription
     */
    constructor() { 
        
        ValidationErrorDescription.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ValidationErrorDescription</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Model/ValidationErrorDescription} obj Optional instance to populate.
     * @return {module:Model/ValidationErrorDescription} The populated <code>ValidationErrorDescription</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ValidationErrorDescription();

            if (data.hasOwnProperty('error')) {
                obj['error'] = ApiClient.convertToType(data['error'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Describes what the problem is with the field
 * @member {String} error
 */
ValidationErrorDescription.prototype['error'] = undefined;






export default ValidationErrorDescription;

