/**
 * TransferZero API
 * Reference documentation for the TransferZero API V1
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TransferzeroSdk);
  }
}(this, function(expect, TransferzeroSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TransferzeroSdk.Debit();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Debit', function() {
    it('should create an instance of Debit', function() {
      // uncomment below and update the code to test Debit
      //var instane = new TransferzeroSdk.Debit();
      //expect(instance).to.be.a(TransferzeroSdk.Debit);
    });

    it('should have the property amount (base name: "amount")', function() {
      // uncomment below and update the code to test the property amount
      //var instane = new TransferzeroSdk.Debit();
      //expect(instance).to.be();
    });

    it('should have the property currency (base name: "currency")', function() {
      // uncomment below and update the code to test the property currency
      //var instane = new TransferzeroSdk.Debit();
      //expect(instance).to.be();
    });

    it('should have the property toType (base name: "to_type")', function() {
      // uncomment below and update the code to test the property toType
      //var instane = new TransferzeroSdk.Debit();
      //expect(instance).to.be();
    });

    it('should have the property toId (base name: "to_id")', function() {
      // uncomment below and update the code to test the property toId
      //var instane = new TransferzeroSdk.Debit();
      //expect(instance).to.be();
    });

    it('should have the property metadata (base name: "metadata")', function() {
      // uncomment below and update the code to test the property metadata
      //var instane = new TransferzeroSdk.Debit();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new TransferzeroSdk.Debit();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "created_at")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instane = new TransferzeroSdk.Debit();
      //expect(instance).to.be();
    });

    it('should have the property usdAmount (base name: "usd_amount")', function() {
      // uncomment below and update the code to test the property usdAmount
      //var instane = new TransferzeroSdk.Debit();
      //expect(instance).to.be();
    });

    it('should have the property runningBalance (base name: "running_balance")', function() {
      // uncomment below and update the code to test the property runningBalance
      //var instane = new TransferzeroSdk.Debit();
      //expect(instance).to.be();
    });

    it('should have the property errors (base name: "errors")', function() {
      // uncomment below and update the code to test the property errors
      //var instane = new TransferzeroSdk.Debit();
      //expect(instance).to.be();
    });

  });

}));
