/**
 * TransferZero API
 * Reference documentation for the TransferZero API V1
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TransferzeroSdk);
  }
}(this, function(expect, TransferzeroSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TransferzeroSdk.Recipient();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Recipient', function() {
    it('should create an instance of Recipient', function() {
      // uncomment below and update the code to test Recipient
      //var instane = new TransferzeroSdk.Recipient();
      //expect(instance).to.be.a(TransferzeroSdk.Recipient);
    });

    it('should have the property requestedAmount (base name: "requested_amount")', function() {
      // uncomment below and update the code to test the property requestedAmount
      //var instane = new TransferzeroSdk.Recipient();
      //expect(instance).to.be();
    });

    it('should have the property requestedCurrency (base name: "requested_currency")', function() {
      // uncomment below and update the code to test the property requestedCurrency
      //var instane = new TransferzeroSdk.Recipient();
      //expect(instance).to.be();
    });

    it('should have the property payoutMethod (base name: "payout_method")', function() {
      // uncomment below and update the code to test the property payoutMethod
      //var instane = new TransferzeroSdk.Recipient();
      //expect(instance).to.be();
    });

    it('should have the property metadata (base name: "metadata")', function() {
      // uncomment below and update the code to test the property metadata
      //var instane = new TransferzeroSdk.Recipient();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "created_at")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instane = new TransferzeroSdk.Recipient();
      //expect(instance).to.be();
    });

    it('should have the property editable (base name: "editable")', function() {
      // uncomment below and update the code to test the property editable
      //var instane = new TransferzeroSdk.Recipient();
      //expect(instance).to.be();
    });

    it('should have the property inputUsdAmount (base name: "input_usd_amount")', function() {
      // uncomment below and update the code to test the property inputUsdAmount
      //var instane = new TransferzeroSdk.Recipient();
      //expect(instance).to.be();
    });

    it('should have the property mayCancel (base name: "may_cancel")', function() {
      // uncomment below and update the code to test the property mayCancel
      //var instane = new TransferzeroSdk.Recipient();
      //expect(instance).to.be();
    });

    it('should have the property stateReason (base name: "state_reason")', function() {
      // uncomment below and update the code to test the property stateReason
      //var instane = new TransferzeroSdk.Recipient();
      //expect(instance).to.be();
    });

    it('should have the property state (base name: "state")', function() {
      // uncomment below and update the code to test the property state
      //var instane = new TransferzeroSdk.Recipient();
      //expect(instance).to.be();
    });

    it('should have the property transactionId (base name: "transaction_id")', function() {
      // uncomment below and update the code to test the property transactionId
      //var instane = new TransferzeroSdk.Recipient();
      //expect(instance).to.be();
    });

    it('should have the property transactionState (base name: "transaction_state")', function() {
      // uncomment below and update the code to test the property transactionState
      //var instane = new TransferzeroSdk.Recipient();
      //expect(instance).to.be();
    });

    it('should have the property exchangeRate (base name: "exchange_rate")', function() {
      // uncomment below and update the code to test the property exchangeRate
      //var instane = new TransferzeroSdk.Recipient();
      //expect(instance).to.be();
    });

    it('should have the property feeFractional (base name: "fee_fractional")', function() {
      // uncomment below and update the code to test the property feeFractional
      //var instane = new TransferzeroSdk.Recipient();
      //expect(instance).to.be();
    });

    it('should have the property inputAmount (base name: "input_amount")', function() {
      // uncomment below and update the code to test the property inputAmount
      //var instane = new TransferzeroSdk.Recipient();
      //expect(instance).to.be();
    });

    it('should have the property inputCurrency (base name: "input_currency")', function() {
      // uncomment below and update the code to test the property inputCurrency
      //var instane = new TransferzeroSdk.Recipient();
      //expect(instance).to.be();
    });

    it('should have the property outputAmount (base name: "output_amount")', function() {
      // uncomment below and update the code to test the property outputAmount
      //var instane = new TransferzeroSdk.Recipient();
      //expect(instance).to.be();
    });

    it('should have the property outputCurrency (base name: "output_currency")', function() {
      // uncomment below and update the code to test the property outputCurrency
      //var instane = new TransferzeroSdk.Recipient();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new TransferzeroSdk.Recipient();
      //expect(instance).to.be();
    });

    it('should have the property errors (base name: "errors")', function() {
      // uncomment below and update the code to test the property errors
      //var instane = new TransferzeroSdk.Recipient();
      //expect(instance).to.be();
    });

  });

}));
