/**
 * TransferZero API
 * Reference documentation for the TransferZero API V1
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TransferzeroSdk);
  }
}(this, function(expect, TransferzeroSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TransferzeroSdk.Transaction();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Transaction', function() {
    it('should create an instance of Transaction', function() {
      // uncomment below and update the code to test Transaction
      //var instane = new TransferzeroSdk.Transaction();
      //expect(instance).to.be.a(TransferzeroSdk.Transaction);
    });

    it('should have the property inputCurrency (base name: "input_currency")', function() {
      // uncomment below and update the code to test the property inputCurrency
      //var instane = new TransferzeroSdk.Transaction();
      //expect(instance).to.be();
    });

    it('should have the property payinMethods (base name: "payin_methods")', function() {
      // uncomment below and update the code to test the property payinMethods
      //var instane = new TransferzeroSdk.Transaction();
      //expect(instance).to.be();
    });

    it('should have the property metadata (base name: "metadata")', function() {
      // uncomment below and update the code to test the property metadata
      //var instane = new TransferzeroSdk.Transaction();
      //expect(instance).to.be();
    });

    it('should have the property sender (base name: "sender")', function() {
      // uncomment below and update the code to test the property sender
      //var instane = new TransferzeroSdk.Transaction();
      //expect(instance).to.be();
    });

    it('should have the property recipients (base name: "recipients")', function() {
      // uncomment below and update the code to test the property recipients
      //var instane = new TransferzeroSdk.Transaction();
      //expect(instance).to.be();
    });

    it('should have the property traits (base name: "traits")', function() {
      // uncomment below and update the code to test the property traits
      //var instane = new TransferzeroSdk.Transaction();
      //expect(instance).to.be();
    });

    it('should have the property state (base name: "state")', function() {
      // uncomment below and update the code to test the property state
      //var instane = new TransferzeroSdk.Transaction();
      //expect(instance).to.be();
    });

    it('should have the property inputAmount (base name: "input_amount")', function() {
      // uncomment below and update the code to test the property inputAmount
      //var instane = new TransferzeroSdk.Transaction();
      //expect(instance).to.be();
    });

    it('should have the property payinReference (base name: "payin_reference")', function() {
      // uncomment below and update the code to test the property payinReference
      //var instane = new TransferzeroSdk.Transaction();
      //expect(instance).to.be();
    });

    it('should have the property paidAmount (base name: "paid_amount")', function() {
      // uncomment below and update the code to test the property paidAmount
      //var instane = new TransferzeroSdk.Transaction();
      //expect(instance).to.be();
    });

    it('should have the property dueAmount (base name: "due_amount")', function() {
      // uncomment below and update the code to test the property dueAmount
      //var instane = new TransferzeroSdk.Transaction();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "created_at")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instane = new TransferzeroSdk.Transaction();
      //expect(instance).to.be();
    });

    it('should have the property expiresAt (base name: "expires_at")', function() {
      // uncomment below and update the code to test the property expiresAt
      //var instane = new TransferzeroSdk.Transaction();
      //expect(instance).to.be();
    });

    it('should have the property externalId (base name: "external_id")', function() {
      // uncomment below and update the code to test the property externalId
      //var instane = new TransferzeroSdk.Transaction();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new TransferzeroSdk.Transaction();
      //expect(instance).to.be();
    });

    it('should have the property errors (base name: "errors")', function() {
      // uncomment below and update the code to test the property errors
      //var instane = new TransferzeroSdk.Transaction();
      //expect(instance).to.be();
    });

  });

}));
