/**
 * TransferZero API
 * Reference documentation for the TransferZero API V1
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TransferzeroSdk);
  }
}(this, function(expect, TransferzeroSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TransferzeroSdk.WebhookLogMetadata();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('WebhookLogMetadata', function() {
    it('should create an instance of WebhookLogMetadata', function() {
      // uncomment below and update the code to test WebhookLogMetadata
      //var instane = new TransferzeroSdk.WebhookLogMetadata();
      //expect(instance).to.be.a(TransferzeroSdk.WebhookLogMetadata);
    });

    it('should have the property params (base name: "params")', function() {
      // uncomment below and update the code to test the property params
      //var instane = new TransferzeroSdk.WebhookLogMetadata();
      //expect(instance).to.be();
    });

    it('should have the property event (base name: "event")', function() {
      // uncomment below and update the code to test the property event
      //var instane = new TransferzeroSdk.WebhookLogMetadata();
      //expect(instance).to.be();
    });

    it('should have the property instanceId (base name: "instance_id")', function() {
      // uncomment below and update the code to test the property instanceId
      //var instane = new TransferzeroSdk.WebhookLogMetadata();
      //expect(instance).to.be();
    });

    it('should have the property instanceType (base name: "instance_type")', function() {
      // uncomment below and update the code to test the property instanceType
      //var instane = new TransferzeroSdk.WebhookLogMetadata();
      //expect(instance).to.be();
    });

    it('should have the property attemptId (base name: "attempt_id")', function() {
      // uncomment below and update the code to test the property attemptId
      //var instane = new TransferzeroSdk.WebhookLogMetadata();
      //expect(instance).to.be();
    });

    it('should have the property tries (base name: "tries")', function() {
      // uncomment below and update the code to test the property tries
      //var instane = new TransferzeroSdk.WebhookLogMetadata();
      //expect(instance).to.be();
    });

    it('should have the property request (base name: "request")', function() {
      // uncomment below and update the code to test the property request
      //var instane = new TransferzeroSdk.WebhookLogMetadata();
      //expect(instance).to.be();
    });

    it('should have the property response (base name: "response")', function() {
      // uncomment below and update the code to test the property response
      //var instane = new TransferzeroSdk.WebhookLogMetadata();
      //expect(instance).to.be();
    });

    it('should have the property appId (base name: "app_id")', function() {
      // uncomment below and update the code to test the property appId
      //var instane = new TransferzeroSdk.WebhookLogMetadata();
      //expect(instance).to.be();
    });

    it('should have the property apiKeyId (base name: "api_key_id")', function() {
      // uncomment below and update the code to test the property apiKeyId
      //var instane = new TransferzeroSdk.WebhookLogMetadata();
      //expect(instance).to.be();
    });

  });

}));
